[
    ActiveDOMObject,
    Constructor(DOMString scriptUrl),
    ConstructorCallWith=ExecutionContext,
    RaisesException=Constructor,
] interface LayoutWorker : EventTarget {
    readonly attribute DOMString type;
    double invoke(double a, double b);

};
LayoutWorker implements AbstractWorker;
