[
    Custom=ToV8,
] interface LayoutGlobalScope : EventTarget {
    [Replaceable] readonly attribute LayoutGlobalScope self;
    attribute Function fn;

    attribute Function calculateMinContentInlineSize;
    attribute Function calculateMaxContentInlineSize;
    attribute Function calculateWidth; // should be calculateInlineSize
    attribute Function calculateHeight; // should be calculateBoxSize?
    attribute Function positionChildren;
};
LayoutGlobalScope implements WindowBase64;
