interface LayoutChild {
    DOMString getCSSValue(DOMString value);

    double maxContentInlineSize();
    double minContentInlineSize();
    void setPosition(double x, double y); // TODO better names for x, y.

    void constrainWidth(double width);
    void clearOverrideSize();

    double measureWidth();
    double measureWidthUsing(DOMString widthStr, double availibleSpace, boolean mainSize);
    [CallWith=ScriptState] Promise<double> measureWidthUsingFixed(double widthPx, double availibleSpace, boolean mainSize);
    double measureHeight();
    [CallWith=ScriptState] Promise<double> measureHeightAndConstrain(double width);

    readonly attribute double width;
    readonly attribute double height;
};
